name: Go-lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GO_VER: "1.22"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VER }}

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Build
      run: make build

  lint:
    name: Run golangci-lint
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VER }}

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: latest
